[aws]
symbol = " "
style = "#232F3E"

[cmd_duration]
style = "white"
prefix = "祥"
min_time = 2000

[directory]
truncation_length = 8

[docker]
disabled = false
symbol = "  "
only_with_files = true
style = "#2496ED"

[git_branch]
symbol = " "
style = "bold #F05032"
truncation_length = 8
truncation_symbol = ""

[git_commit]
style = "dimmed #F05032"

[git_status]
style = "#F05032"
prefix = ""
suffix = " "
show_sync_count = true
conflicted_count.enabled = true
deleted_count.enabled = true
modified_count.enabled = true
stashed_count.enabled = true
staged_count.enabled = true
renamed_count.enabled = true
untracked_count.enabled = true

[memory_usage]
disabled = false
symbol = " "
style = "dimmed green"
show_percentage = true
show_swap = false
threshold = 75

[terraform]
symbol = " "
style = "#623CE4"

[username]
disabled = false
show_always = true