[aws]
symbol = " "
style = "bold #232F3E"

[cmd_duration]
style = "none"
format = "羽[$duration]($style)"
min_time = 300000

[directory]
truncation_length = 8
read_only = " "

[docker_context]
disabled = false
symbol = " "
style = "bold #2496ED"
only_with_files = true

[git_branch]
symbol = " "
style = "bold #F05032"
truncation_length = 8

[git_commit]
style = "dimmed #F05032"

[git_status]
style = "#F05032"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
conflicted = "=${count}"
untracked = "?${count}"
stashed = "$${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[jobs]
threshold = 4

[memory_usage]
disabled = false
symbol = " "
style = "dimmed green"
threshold = 75
format = "$symbol [${ram_pct}]$(style) "

[terraform]
symbol = "ﲴ "
style = "bold #623CE4"

[time]
style = "none"
time_format = "%T"
format = "[$time]($style)"

[username]
disabled = false
show_always = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "